## This is an example configuration file for the bot.
## Make sure to edit it prior to using it.

# The token for the bot.
token: mfa.exampletoken

# The command prefix used by the bot.
command_prefix: '!!'

cogs:
  - utility